name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run:
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run:
          pwd
          ls
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: Miguelito
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"

