name: Shell Commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello man"
      - name: multiline
        run: | 
          node -v
          npm -v
      - name: pythin command 
        run: | 
          import platform
          print(platform.processor())
        shell: python
  run-windows-comands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash



